version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/deregister_from_elb.sh
      timeout: 300
      runas: ubuntu
  BeforeInstall:
    - location: scripts/install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: scripts/register_with_elb.sh
      timeout: 300
      runas: ubuntu
