[app]
    hostname = "https://api-web.int.dev.razorpay.com"

[paymentpage]
    user = "7HQnhEQDgBIdlv"
    role = "owner"
    username = "rzp_test_10000000000000"
    password = "RANDOM_DASH_PASSWORD"

[OneClickCheckout]
    username = "rzp_test_0Vsp9weqfeCcKw"
    password = "dm2ANMx5K5NrSG18zRiUey83"

[Payments]
    username = "rzp_test_1DP5mmOlF5G5ag"
    password = "thisissupersecret"

[SubMerchant]
    user = "7HQnhEQDgBIdlv"
    role = "owner"
    username = "rzp_test_10000000000000"
    liveUsername = "rzp_live_10000000000000"
    password = "RANDOM_DASH_PASSWORD"
    rzpSuperKey="rzp_test"
    rzpSuperSecret="DASHBOARD_AUTH_PASS_STAGING"

[apidb]
    [apidb.connectionconfig]
        dialect               = "mysql"
        protocol              = "tcp"
        url                   = "beta-api-db.np.razorpay.vpc."
        port                  = 3306
        username              = "api-beta-test"
        sslMode               = "require"
        name                  = "api-beta-test"

    [apidb.connectionpoolconfig]
        maxopenconnections    = 5
        maxidleconnections    = 5
        connectionMaxLifetime = 0

[virtualaccount]
    user = "7HQnhEQDgBIdlv"
    role = "owner"
    merchantId = "CeSoV4pBMpqFJ4"
    username = "rzp_test_rGwnJw1UOFxJuk"
    password = "r9NAWAwHFbrzyzPTFSJhnX7X"

[onboardingapispartner]
    user = "LdXLKyZg5VLZvz"
    role = "owner"
    merchantId = "LdXLL1OsHXpVeH"
    username = "rzp_live_partner_LdXSPcmuVH7rLq"
    password = "9dLdThIWVhvxGGPncR5v7KOR"

[adminconfig]
    username = "rzp_test"
    password = "RANDOM_DASH_PASSWORD"
    orgId = "org_100000razorpay"
    token = "hello7gyptrWlOKu6z9"
