name: Delete Api docs

on:
  push:
  delete:

jobs:
  delete-temporary-api-details-files:
    name: Remove previous Temporary files
    runs-on: [ self-hosted ]
    steps:
      - name: set repo env
        run: echo "REPO=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_ENV
      - name: s3 rm
        uses: docker://amazon/aws-cli:2.2.25
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ACTIONS_CACHE_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.ACTIONS_CACHE_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{secrets.ACTIONS_CACHE_AWS_REGION}}
        with:
          args: s3 rm s3://rzp-actions-cache/_docs/${{ env.REPO }}/  --recursive
  delete-api-docs:
    name: Remove deleted branch's api docs from idocs
    if: github.event_name == 'delete' && github.event.ref_type == 'branch'
    runs-on: [api-public]
    steps:
      - name: set repo env
        run: echo "REPO=$(echo ${GITHUB_REPOSITORY##*/})" >> $GITHUB_ENV
      - name: s3 rm
        uses: docker://amazon/aws-cli:2.2.25
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.IDOCS_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.IDOCS_AWS_SECRET_ACCESS_KEY }}
        with:
          args: s3 rm s3://rzp-idocs/_docs/${{ env.REPO }}/${{ github.event.ref }}.json
