on:
  push:
    branches-ignore:
      - '**'
name: Mandatory-Jira-Check
jobs:

  Find-Jira-Id:
    name: Find-Jira-Id
    runs-on: [api-public]

    steps:
      - name: Checkout
        uses: razorpay/checkout-action@08eef2bd6ada50786812e7351457a762856a532f

      - name: Checkout GitHub Action Repo
        uses: razorpay/checkout-action@08eef2bd6ada50786812e7351457a762856a532f
        with:
          repository: Razorpay/check-commit-jira
          path: .github/actions/check-commit-jira
          ref:  ignore_status
          token: ${{ secrets.GIT_TOKEN }}

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      #  Find Issue on JIRA
      - name: Get Issue Key
        id: find
        uses: ./.github/actions/check-commit-jira
        with:
          from: pull_request
      #  Print JIRA ID found on jira
      - name: Find issue info
        run: echo "Issue ${{ steps.find.outputs.issue }} was found"
