name: Report Rate Limit
on:
  push:
  schedule:
    - cron: '*/15 * * * *'
jobs:
  slack-notify:
    runs-on: [ api-public ]
    steps:
      # This gets the rate limit for the default github.token that is a per-repo rate limit.
      - id: get_rate_limit
        name: Get Rate Limit Utilization
        run: |
          curl -H 'Accept: application/vnd.github.v3+json' -H 'Authorization: token ${{github.token}}' https://api.github.com/rate_limit > rate_limit.json
          cat rate_limit.json
          utilization=$(cat rate_limit.json | jq '.rate.used/.rate.limit*100')
          echo "::set-output name=utilization::$(printf '%.2f' $utilization)"
      - name: Report current GitHub Actions Rate Limit to Slack
        if: ${{steps.get_rate_limit.outputs.utilization > 75}}
        env:
          SLACK_MESSAGE: "Utilization: ${{ steps.get_rate_limit.outputs.utilization }}%"
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_USERNAME: "Rate Limit: ${{github.repository}}"
          SLACK_MSG_AUTHOR: ""
          SLACK_CHANNEL: tech_alerts
          SLACK_ICON: https://github.githubassets.com/favicons/favicon.png
          SLACK_FOOTER: ""
          MSG_MINIMAL: actions url
          SLACK_COLOR: red
        uses: rtCamp/action-slack-notify@c753c78497b021971cf6540efe8c3a131e4b702f
